spring:
  main:
    web-application-type: none
  aop:
    proxy-target-class: false
job:
  insight:
    cron: 0 * * * * ?

datasources:
  datasources:
    -
      enabled: true
      name: mysql
      hikari:
        maximum-pool-size: 10
        max-lifetime: 1800000
        minimum-idle: 1
        pool-name: MySql Query Pool
        jdbc-url: jdbc:mysql://localhost:3306/MYSQLDB
        username: USERNAME
        password: PASSWORD
        driver-class-name: com.mysql.cj.jdbc.Driver
        connection-test-query: SELECT 1
    -
      enabled: true
      name: mysql1
      hikari:
        maximum-pool-size: 10
        max-lifetime: 1800000
        minimum-idle: 1
        pool-name: MySql1 Query Pool
        jdbc-url: jdbc:mysql://localhost:3306/MYSQL_ANOTHER_DB
        username: USERNAME
        password: PASSWORD
        driver-class-name: com.mysql.cj.jdbc.Driver
        connection-test-query: SELECT 1
    -
      enabled: true
      name: oracle
      hikari:
        jdbc-url: jdbc:oracle:thin:@//HOST_NAME:1521/SERVICE_NAME
        username: USERNAME
        password: PASSWORD
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        maximum-pool-size: 10
        max-lifetime: 1800000
        minimum-idle: 1
        pool-name: Oracle Query Pool
    -
      enabled: true
      name: postgre
      hikari:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:postgresql://localhost:5432/POSTGRES_DB
        username: USERNAME
        password: PASSWORD
        driver-class-name: org.postgresql.Driver
        maximum-pool-size: 10
        max-lifetime: 1800000
        minimum-idle: 1
        connection-test-query: SELECT 1
        pool-name: Postgres Query Pool
    -
      enabled: false
      name: sqlserver
      hikari:
       type: com.zaxxer.hikari.HikariDataSource
       url: jdbc:sqlserver://localhost;databaseName=SQL_SERVER_DB
       username: USERNAME
       password: PASSWORD
       driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
       maximum-pool-size: 10
       max-lifetime: 1800000
       minimum-idle: 1
       connection-test-query: SELECT 1
       pool-name: Sql Server Query Pool

newrelic:
  inights-insert-key: NEWRELIC_INSIGHT_INSERT_KEY
  insights-insert-url: NEWRELIC_INSIGHT_INSERT_URL

db:
  queries:
    -
      sql: "QUERY"
      datasourceName: mysql # datasource to use for query
      insightEventType: MySqlTestEvents # Newrelic Insight Event name
    -
      sql: "QUERY"
      datasourceName: mysql # datasource to use for query
      insightEventType: MySqlTestEvents # Newrelic Insight Event name
    -
      sql: "QUERY"
      datasourceName: mysql1 # datasource to use for query
      insightEventType: MySql1TestEvents # Newrelic Insight Event name
    -
      sql: "QUERY"
      datasourceName: postgre # datasource to use for query
      insightEventType: PostgreTestEvents # Newrelic Insight Event name
